### ISSUE TITLE
Status not reset after sleep is triggered

### ISSUE THREAD

**Issue by lameventanas** [robwebset/script.sleep#1]
There is a bug somewhere in this plugin, I can reproduce it as follows:
1. Start playing a video
2. Activate sleep "on video end"
3. Video ends, shutdown script runs

At this point one would expect that the "on video end" sleep being disabled, but if you play a new video, the shutdown script will run again once the video ends.

**Comment by robwebset** [comment]
I haven't managed to reproduce this problem, but reading the code I can see one possible route it could take that MAY cause this issue, I have made a change in version v1.2.4

https://github.com/robwebset/repository.robwebset/raw/master/script.sleep/script.sleep-1.2.4.zip

Please can you give it a go and let me know if it solves your issue.

Thanks
Rob

**Comment by lameventanas** [comment]
Yes, this fixes it, thanks!

Also, please create a tag with each version bump, it makes life easier for packagers/people that distribute kodi with pre-installed plugins.

**Comment by robwebset** [comment]
Thanks for confirming - nobody should be pre-bundling my addons in anything - it is against the license.

Rob

**Comment by lameventanas** [comment]
That was just one example, creating tags is a good practice anyway, at least for mayor version changes.

The wiki says your addon is GPL v3.0.  If for whatever reason if you decided to change the license to something more restrictive, you should update the wiki too.

**Comment by robwebset** [comment]
The wiki is the Kodi teams - not mine - see:
https://github.com/robwebset/script.sleep
